---
- name: Ensure SSH daemon is running.
  service:
    name: "{{ security_sshd_name }}"
    state: "{{ security_sshd_state }}"

- name: Update SSH configuration to be more secure.
  lineinfile:
    dest: "{{ security_ssh_config_path }}"
    regexp: '^(?:#\s*)?{{ item.key }}\s'
    line: "{{ item.key }} {{ item.value }}"
    state: present
    validate: 'sshd -T -f %s'
    mode: 0644
  with_items:
    - key: PubkeyAuthentication
      value: "{{ security_ssh_password_authentication }}"
    - key: PermitRootLogin
      value: "{{ security_ssh_permit_root_login }}"
    - key: Port
      value: "{{ security_ssh_port }}"
    - key: UseDNS
      value: "{{ security_ssh_usedns }}"
    - key: PermitEmptyPasswords
      value: "{{ security_ssh_permit_empty_password }}"
    - key: ChallengeResponseAuthentication
      value: "{{ security_ssh_challenge_response_auth }}"
    - key: GSSAPIAuthentication
      value: "{{ security_ssh_gss_api_authentication }}"
    - key: X11Forwarding
      value: "{{ security_ssh_x11_forwarding }}"
  notify: restart ssh

- name: Add configured users allowed to connect over ssh
  lineinfile:
    dest: "{{ security_ssh_config_path }}"
    regexp: '^(?:#\s*)?AllowUsers\s'
    line: "AllowUsers {{ security_ssh_allowed_users | join(' ') }}"
    state: present
    create: true
    validate: 'sshd -T -f %s'
    mode: 0644
  when: security_ssh_allowed_users | length > 0
  notify: restart ssh

- name: Add configured groups allowed to connect over ssh
  lineinfile:
    dest: "{{ security_ssh_config_path }}"
    regexp: '^(?:#\s*)?AllowGroups\s'
    line: "AllowGroups {{ security_ssh_allowed_groups | join(' ') }}"
    state: present
    create: true
    validate: 'sshd -T -f %s'
    mode: 0644
  when: security_ssh_allowed_groups | length > 0
  notify: restart ssh

- name: Add configured user accounts to passwordless sudoers.
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0440
  with_items: "{{ security_sudoers_passwordless }}"
  when: security_sudoers_passwordless | length > 0

- name: Add configured user accounts to passworded sudoers.
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0440
  with_items: "{{ security_sudoers_passworded }}"
  when: security_sudoers_passworded | length > 0
